language: ruby
dist: trusty

rvm:
  - jruby-head

jdk:
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

notifications:
  email: false
